coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: no
    patch: yes
    changes: no

comment:
  layout: "header, diff, changes, tree"
  behavior: default

ignore:
  - "Example/.*"
  - "Example"
  - "Example/*"
  - "SSegmentRecordingView"
  - "Example/Tests"
  - "Tests"
  - "./Example/Tests"
  - "./SSegmentRecordingView_Example.app.coverage.txt"
  - "[a-z]+/_Test.*"  # regexp accepted
