language: objective-c
osx_image: xcode10
podfile: Example/Podfile

branches:
  only:
    - develop
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - rvm install ruby-2.4.0
  - gem install xcpretty -N
  - gem install cocoapods
  - pod repo update
script:
  - set -o pipefail
  - cd Example
  - xcodebuild -workspace SSegmentRecordingView.xcworkspace -scheme SSegmentRecordingView_Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - xcodebuild test -workspace SSegmentRecordingView.xcworkspace -scheme SSegmentRecordingView_Tests -destination 'platform=iOS Simulator,name=iPhone XS,OS=12.0' | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)