language: swift
xcode_project: Example/SSegmentRecordingView.xcodeproj # path to your xcodeproj folder
xcode_scheme: SSegmentRecordingView_Tests
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone XR
podfile: Example/Podfile