language: objective-c
osx_image: xcode10.2
podfile: Example/Podfile

branches:
  only:
    - develop
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - rvm install ruby-2.4.0
  - gem install xcpretty -N
  - gem install cocoapods
  - pod repo update
script:
  - set -o pipefail
  - xcodebuild test -workspace Example/SSegmentRecordingView.xcworkspace -scheme SSegmentRecordingView_Tests -destination 'platform=iOS Simulator,name=iPhone XS,OS=12.2' -enableCodeCoverage YES VALID_ARCHS=x86_64 ONLY_ACTIVE_ARCH=NO -derivedDataPath ./DerivedData | xcpretty -c "--report" "html" "--output" "./ProjectReport.html"
after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f Coverage/cobertura.xml -X coveragepy -X gcov -X xcode